upload

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -34,14 +34,22 @@ jobs:
       env:
         HUGO_ENVIRONMENT: production
       run: |
-        hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
-    - name: Debug build output
-      run: ls -l ./public
+        set -e
+        hugo --minify --baseURL "${{ github.event.repository.html_url }}"
+    - name: Debug Hugo output
+      run: |
+        if [ -d "./public" ]; then 
+          echo "Public folder exists."; 
+          ls -lah ./public;
+        else 
+          echo "Public folder is missing!"; 
+          exit 1;
+        fi
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: github-pages
-        path: ./public
+        path: ./public/
 
   deploy:
     runs-on: ubuntu-latest
