upload

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -1,4 +1,4 @@
-name: Deploy website to GitHub Pages
+name: Deploy to GitHub Pages
 
 env:
   WC_HUGO_VERSION: '0.136.5'
@@ -21,36 +21,36 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - name: Setup Hugo
-      uses: peaceiris/actions-hugo@v3
-      with:
-        hugo-version: ${{ env.WC_HUGO_VERSION }}
-        extended: true
-    - name: Build with Hugo
-      env:
-        HUGO_ENVIRONMENT: production
-      run: |
-        set -e
-        hugo --minify --baseURL "${{ github.event.repository.html_url }}"
-    - name: Debug Hugo output
-      run: |
-        if [ -d "./public" ]; then 
-          echo "Public folder exists."; 
-          ls -lah ./public;
-        else 
-          echo "ERROR: Public folder is missing!"; 
-          exit 1;
-        fi
-    - name: Upload artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: github-pages
-        path: ./public/
-        retention-days: 1
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Setup Hugo
+        uses: peaceiris/actions-hugo@v3
+        with:
+          hugo-version: ${{ env.WC_HUGO_VERSION }}
+          extended: true
+      - name: Build with Hugo
+        env:
+          HUGO_ENVIRONMENT: production
+        run: |
+          set -e
+          hugo --minify --baseURL "${{ github.event.repository.html_url }}"
+      - name: Debug Hugo output
+        run: |
+          if [ -d "./public" ]; then 
+            echo "Public folder exists."; 
+            ls -lah ./public;
+          else 
+            echo "ERROR: Public folder is missing!"; 
+            exit 1;
+          fi
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: github-pages
+          path: ./public/
+          retention-days: 1
 
   deploy:
     runs-on: ubuntu-latest
@@ -59,20 +59,23 @@ jobs:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     steps:
-    - name: Download artifact
-      uses: actions/download-artifact@v3
-      with:
-        name: github-pages
-        path: ./public
-    - name: Debug downloaded artifact
-      run: |
-        if [ -d "./public" ]; then 
-          echo "Downloaded artifact exists."; 
-          ls -lah ./public;
-        else 
-          echo "ERROR: No artifact found!"; 
-          exit 1;
-        fi
-    - name: Deploy to GitHub Pages
-      id: deployment
-      uses: actions/deploy-pages@v2
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: github-pages
+          path: ./public
+      - name: Debug downloaded artifact
+        run: |
+          if [ -d "./public" ]; then 
+            echo "Downloaded artifact exists."; 
+            ls -lah ./public;
+          else 
+            echo "ERROR: No artifact found!"; 
+            exit 1;
+          fi
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./public
